version: '3.8'
services:
    sc5_php:
        build: ./docker/php
        volumes:
            - .:/var/www/
            # - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        networks:
         - sc5-network

networks:
  sc5-network:
    driver: bridge        
    # mysql:
    #     image: 'mysql:8.0'
    #     working_dir: /application
    #     volumes:
    #         - '.:/application'
    #     environment:
    #         - MYSQL_ROOT_PASSWORD=demo
    #         - MYSQL_DATABASE=demo
    #         - MYSQL_USER=demo
    #         - MYSQL_PASSWORD=demo
    #     ports:
    #         - '29002:3306'

    # mariadb:
    #     image: 'mariadb:10.6'
    #     working_dir: /application
    #     volumes:
    #         - '.:/application'
    #     environment:
    #         - MYSQL_ROOT_PASSWORD=demo
    #         - MYSQL_DATABASE=demo
    #         - MYSQL_USER=demo
    #         - MYSQL_PASSWORD=demo
    #     ports:
    #         - '29003:3306'

    # postgres:
    #     image: 'postgres:11.1-alpine'
    #     working_dir: /application
    #     volumes:
    #         - '.:/application'
    #     environment:
    #         - POSTGRES_USER=demo
    #         - POSTGRES_PASSWORD=demo
    #         - POSTGRES_DB=demo
    #     ports:
    #         - '29004:5432'

    # webserver:
    #     image: 'nginx:alpine'
    #     working_dir: /application
    #     volumes:
    #         - '.:/application'
    #         - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    #     ports:
    #         - '29000:80'

   
